{
 "title": "Acme Inc.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# ACME Inc." } },
  {
   "title": "Replicas - Web",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"acme-welcome-page.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas - App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"acme-inc-app-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Welcome page - CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "irate(container_cpu_user_seconds_total{pod=~\"acme-welcome-page-.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Welcome page - Mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"acme-welcome-page-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Welcome page - CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "irate(container_cpu_user_seconds_total{pod=~\"acme-inc-app-.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "App- Mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"acme-inc-app-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Welcome page - logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{app=\"acme-welcome-page\"} |= ``"
    }
   ]
  },
  {
   "title": "App - logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{app=\"acme-inc-app\"} |= ``"
    }
   ]
  }
 ]
}