apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-welcome-page
  labels:
    app: acme-welcome-page
    company: acme
spec:
  replicas: 10
  selector:
    matchLabels:
      app: acme-welcome-page
      company: acme
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: acme-welcome-page
        company: acme
    spec:
      containers:
      - name: acme-welcome-page
        image: localhost:30335/acme-inc-welcome-page:3
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: acme-welcome-page
spec:
  selector:
    app: acme-welcome-page
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30900
