apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-inc-app
  labels:
    app: acme-inc-app
    company: acme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: acme-inc-app
      company: acme
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: acme-inc-app
        company: acme
    spec:
      containers:
      - name: acme-inc-app
        image: localhost:30335/acme-inc-app:1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: acme-inc-app
spec:
  selector:
    app: acme-inc-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30980
      name: http
