apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-page
  namespace: continuous-integration
  labels:
    app: welcome-page
    company: acme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome-page
      company: acme
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: welcome-page
        company: acme
    spec:
      containers:
      - name: nginx
        image: localhost:30335/app:.TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: welcome-page
  namespace: continuous-integration
spec:
  selector:
    app: welcome-page
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9000
      name: http
