apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
  annotations:
    null
spec:
  type: NodePort
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30335
  selector:
    app: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
            name: registry
            protocol: TCP
        env:
          - name: REGISTRY_HTTP_ADDR
            value: :5000
          - name: REGISTRY_STORAGE_DELETE_ENABLED
            value: "yes"
